apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-gcp"
  description: "test"
  annotations:
    github.com/project-slug: "blamdemo/my-test-thing-gcp"
    backstage.io/techdocs-ref: github:https://github.com/blamdemo/my-test-thing-gcp
spec:
  type: service
  lifecycle: experimental
  owner: "guest"
